SELECT
        CAND_NAME,
        CAND_OFFICE_ST,
        SUM(TRANSACTION_AMT)
    FROM
        INDIV_CONTRIB
    JOIN
        CANDIDATE
            ON INDIV_CONTRIB.CMTE_ID = CANDIDATE.CAND_PCC
    WHERE
        ENTITY_TP = "IND"
        AND CAND_OFFICE = 'S'
        AND CAND_STATUS IN ('C', 'N')
        AND CAND_ELECTION_YR = 2016
        AND INDIV_CONTRIB.STATE !=  CANDIDATE.CAND_OFFICE_ST
    GROUP BY
        1,
        2
    ORDER BY
        3 DESC
    LIMIT 5;
