SELECT
        CAND_PTY_AFFILIATION,
        SUM(TTL_INDIV_CONTRIB),
        SUM(TTL_RECEIPTS),
        SUM(TTL_INDIV_CONTRIB)/SUM(TTL_RECEIPTS) AS RATIO_INDIV
    FROM
        CANDIDATE
    join
        CAND_SUMMARY
          ON CANDIDATE.CAND_ID = CAND_SUMMARY.CAND_ID
    WHERE
        CAND_OFFICE = 'S'
        AND CAND_STATUS IN ('C', 'N')
        AND CAND_ELECTION_YR = 2016
    GROUP BY
        1
    ORDER BY
        RATIO_INDIV DESC
    LIMIT 10;
