SELECT CAND_PTY_AFFILIATION,COUNT(CAND_ID) FROM CANDIDATE
    WHERE CAND_OFFICE = 'S'
          AND CAND_STATUS IN ('C', 'N')
          AND CAND_ELECTION_YR = 2016
          AND NOT CAND_PTY_AFFILIATION IN ('REP','IND','DEM')
    GROUP BY 1
    ORDER BY 2 DESC;
