SELECT
        INDIV_CONTRIB.STATE,
        SUM(TRANSACTION_AMT)/POPULATION AS AMT_PER_CAPITA
    FROM
        INDIV_CONTRIB
    JOIN
        DIST_POP
            ON INDIV_CONTRIB.STATE = DIST_POP.STATE
    WHERE
        ENTITY_TP = "IND"
        AND TRANSACTION_TP = "10"
    GROUP BY
        1
    ORDER BY
        2 DESC
    LIMIT 5;
